"""
Sentinel Session Briefing Generator.

Extracted from sentinel.py (S87, ADR-005 Phase 2).
Generates structured markdown briefings for Cowork sessions,
including agent health, governance gate, findings, and system state.
"""
import json
import shutil
from datetime import datetime
from pathlib import Path

from . import LOGS_DIR


def generate_session_briefing(
    state,
    briefing_file,
    observations_file,
    version,
    read_status_fn,
    observe_fn,
):
    """Generate a structured briefing for the next Cowork session.

    Reads agent statuses, pending work, recent observations, and
    produces a markdown file that new sessions should read first.
    Only regenerates every 4th run (~hourly) or when state changes.

    Args:
        state: Sentinel state dict
        briefing_file: Path to write briefing markdown
        observations_file: Path to observations JSON
        version: Sentinel version string
        read_status_fn: callable(agent_name) -> status dict
        observe_fn: callable(category, observation) for logging
    """
    run_count = state.get("run_count", 0)
    if run_count % 4 != 0 and briefing_file.exists():
        return

    try:
        lines = []
        now = datetime.now()
        lines.append(f"# Session Briefing \u2014 {now.strftime('%Y-%m-%d %H:%M')}")
        lines.append(f"*Generated by Sentinel v{version}*\n")

        # Machine state
        total, used, free = shutil.disk_usage("C:\\")
        free_gb = round(free / (1024**3), 1)
        lines.append("## Machine State")
        lines.append(f"- Disk: {free_gb} GB free")
        lines.append(
            f"- Sentinel streak: {state.get('streak', 0)} consecutive healthy runs"
        )
        lines.append(f"- Last Sentinel run: {state.get('last_run', 'unknown')}")
        lines.append("")

        # Agent health summary
        lines.append("## Agent Health")
        agents = [
            "system_master", "security_agent", "sentinel",
            "task_master", "research_intel", "operations_monitor",
        ]
        for agent_name in agents:
            status = read_status_fn(agent_name)
            s = status.get("status", "unknown")
            last = status.get("last_run", "never")
            summary = status.get("summary", "")[:80]
            if s == "ok":
                icon = "+"
            elif s == "warning":
                icon = "!"
            elif s == "error":
                icon = "X"
            else:
                icon = "?"
            lines.append(f"- {icon} **{agent_name}**: {s} (last: {last})")
            if summary:
                lines.append(f"  {summary}")
        lines.append("")

        # Lucius Gate (ADR-004, Session 23)
        _append_governance_gate(lines, state, observe_fn)

        # Open Findings (Session 24)
        _append_findings(lines, state, observe_fn)

        # Registry Stats (Session 24)
        _append_registry_stats(lines)

        # Pending work
        _append_pending_work(lines)

        # Recent crash dumps
        _append_recent_crashes(lines, now)

        # Dependency health
        _append_dependency_health(lines)

        # Recent observations
        _append_observations(lines, observations_file)

        # Available tools reminder
        lines.append("## Reminder: Available Tools")
        lines.append("Before writing custom code, check:")
        lines.append(
            "- `rudy-logs/capability-manifest.json`"
            " -- full index of modules, packages, skills"
        )
        lines.append(
            "- Cowork skills: 30+ across Engineering,"
            " Operations, Productivity, Legal, Plugin Mgmt"
        )
        lines.append(
            "- MCP connectors: Gmail, Google Calendar,"
            " Notion, Canva, Chrome"
        )
        lines.append(
            "- rudy/ modules: 31+ (OCR, NLP, financial,"
            " voice, network defense, etc.)"
        )
        lines.append(
            "- Agent tool: spawn sub-agents for parallel"
            " research/exploration"
        )
        lines.append("")

        # Session activity
        _append_session_activity(lines, now, state)

        briefing_file.write_text("\n".join(lines), encoding="utf-8")
        observe_fn("briefing", "Session briefing updated")

    except Exception as e:
        observe_fn("briefing_error", f"Briefing generation failed: {e}")


def _append_governance_gate(lines, state, observe_fn):
    """Append Lucius governance gate results to briefing."""
    try:
        from rudy.agents.lucius_gate import session_start_gate
        gate_result = session_start_gate(
            session_number=state.get("session_number", 0),
            check_timeout_sec=5.0,
        )
        passed = gate_result.passed
        degraded = getattr(gate_result, "degraded", False)
        if passed:
            gate_icon = "PASS"
        elif degraded:
            gate_icon = "DEGRADED"
        else:
            gate_icon = "FAIL"
        lines.append("## Governance Gate (Lucius)")
        lines.append(f"- **Status**: {gate_icon} -- {gate_result.summary()}")
        for check in gate_result.checks:
            if check.state.value != "PASS":
                lines.append(
                    f"  - {check.name}: {check.state.value}"
                    f" -- {check.message}"
                )
        if gate_result.metrics:
            lines.append(
                f"- Gate completed in"
                f" {gate_result.metrics.total_elapsed_sec:.1f}s"
            )
        lines.append("")
        observe_fn("lucius_gate", f"Session gate: {gate_result.summary()}")
    except ImportError:
        lines.append("## Governance Gate (Lucius)")
        lines.append("- lucius_gate not available (import failed)")
        lines.append("")
    except Exception as e:
        lines.append("## Governance Gate (Lucius)")
        lines.append(f"- Gate check failed: {e}")
        lines.append("")


def _append_findings(lines, state, observe_fn):
    """Append open findings to briefing."""
    try:
        from rudy.agents.lucius_findings import (
            format_findings_briefing,
            escalate_stale_findings,
        )
        session_num = state.get("session_number", 0)
        escalated = escalate_stale_findings(session_num)
        if escalated:
            observe_fn(
                "lucius_findings",
                f"{len(escalated)} findings escalated to HIGH",
            )
        lines.append(format_findings_briefing(max_findings=10))
    except ImportError:
        pass
    except Exception as e:
        lines.append(f"## Open Findings\n\n- Findings check failed: {e}\n")


def _append_registry_stats(lines):
    """Append registry stats to briefing."""
    try:
        from rudy.agents.lucius_registry import build_registry
        registry = build_registry()
        stats = registry.get("stats", {})
        lines.append("## Registry Stats")
        lines.append(
            f"- {stats.get('total_files', '?')} files, "
            f"{stats.get('total_lines', 0):,} lines, "
            f"{stats.get('total_agents', '?')} agents, "
            f"{stats.get('total_skills', '?')} skills, "
            f"{stats.get('total_mcps', '?')} MCPs"
        )
        lines.append(
            f"- Registry scan: {stats.get('scan_duration_sec', '?')}s"
        )
        lines.append("")
    except ImportError:
        pass
    except Exception as e:
        lines.append(f"## Registry Stats\n\n- Registry scan failed: {e}\n")


def _append_pending_work(lines):
    """Append pending work items to briefing."""
    lines.append("## Pending Work")
    queue_file = LOGS_DIR / "task-queue.json"
    if queue_file.exists():
        try:
            queue = json.loads(queue_file.read_text())
            pending = queue.get("pending", [])
            in_progress = queue.get("in_progress", [])
            if pending:
                for item in pending[:5]:
                    desc = (
                        item if isinstance(item, str)
                        else item.get("description", str(item))
                    )
                    lines.append(f"- [ ] {desc}")
            if in_progress:
                for item in in_progress[:3]:
                    desc = (
                        item if isinstance(item, str)
                        else item.get("description", str(item))
                    )
                    lines.append(f"- [~] {desc} (in progress)")
            if not pending and not in_progress:
                lines.append("- No pending tasks")
        except Exception:
            lines.append("- Could not read task queue")
    else:
        lines.append("- No task queue file")
    lines.append("")


def _append_recent_crashes(lines, now):
    """Append recent crash dumps to briefing."""
    crash_dir = LOGS_DIR / "crash-dumps"
    if crash_dir.exists():
        crash_files = sorted(
            crash_dir.glob("*.json"),
            key=lambda f: f.stat().st_mtime,
            reverse=True,
        )
        recent_crashes = [
            f for f in crash_files
            if (now.timestamp() - f.stat().st_mtime) < 86400
        ]
        if recent_crashes:
            lines.append("## Recent Crashes (last 24h)")
            for cf in recent_crashes[:5]:
                try:
                    cd = json.loads(cf.read_text(encoding="utf-8"))
                    lines.append(
                        f"- **{cd.get('agent', '?')}**"
                        f" at {cd.get('crash_time', '?')}:"
                        f" `{cd.get('error_type', '?')}:"
                        f" {cd.get('error_message', '')[:100]}`"
                    )
                except Exception:
                    lines.append(f"- {cf.name} (could not parse)")
            lines.append("")

    # Crash marker cleanup
    marker = LOGS_DIR / "CRASH-DETECTED.txt"
    if marker.exists():
        if not (crash_dir.exists() and any(
            (now.timestamp() - f.stat().st_mtime) < 3600
            for f in crash_dir.glob("*.json")
        )):
            try:
                marker.unlink()
            except Exception:
                pass


def _append_dependency_health(lines):
    """Append dependency health issues to briefing."""
    dep_health = LOGS_DIR / "dependency-health.json"
    if dep_health.exists():
        try:
            dh = json.loads(dep_health.read_text(encoding="utf-8"))
            issues = dh.get("issues", [])
            if issues:
                lines.append("## Dependency Issues")
                for issue in issues[:5]:
                    if issue.get("type") == "superseded":
                        lines.append(
                            f"- **{issue['package']}** is"
                            f" {issue['status']}:"
                            f" use `{issue['replacement']}` instead"
                            f" -- {issue.get('replacement_reason', '')[:80]}"
                        )
                    elif issue.get("type") == "import_failure":
                        lines.append(
                            f"- **{issue['module']}**"
                            f" ({issue['description']}): import failed"
                        )
                lines.append("")
        except Exception:
            pass


def _append_observations(lines, observations_file):
    """Append recent observations to briefing."""
    lines.append("## Recent Observations")
    if observations_file.exists():
        try:
            obs = json.loads(observations_file.read_text())
            actionable = [o for o in obs if o.get("actionable")][-5:]
            if actionable:
                for o in actionable:
                    lines.append(
                        f"- **{o.get('category', '?')}**:"
                        f" {o.get('observation', '')}"
                    )
            else:
                lines.append("- No actionable observations")
        except Exception:
            lines.append("- Could not read observations")
    lines.append("")


def _append_session_activity(lines, now, state):
    """Append session activity and live services to briefing."""
    lines.append("## Session Activity")
    runner_log = LOGS_DIR / "command-runner.log"
    if runner_log.exists():
        age_min = (now.timestamp() - runner_log.stat().st_mtime) / 60
        if age_min < 5:
            lines.append(
                f"- Command runner: active ({age_min:.0f} min ago)"
            )
        elif age_min < 30:
            lines.append(
                f"- Command runner: idle"
                f" ({age_min:.0f} min since last activity)"
            )
        else:
            lines.append(
                f"- Command runner: **inactive**"
                f" ({age_min:.0f} min since last activity)"
            )
    else:
        lines.append("- Command runner: no log found")

    # Live system state
    svc_health = state.get("service_health", {})
    if svc_health:
        lines.append("")
        lines.append("## Live Services")
        for svc, status in svc_health.items():
            up_words = ("running", "connected")
            down_words = ("down", "error", "not running", "disconnected")
            if any(w in status for w in up_words):
                icon = "[UP]"
            elif any(w in status for w in down_words):
                icon = "[DOWN]"
            else:
                icon = "[?]"
            lines.append(f"- {icon} **{svc}**: {status}")

    if state.get("rustdesk_session_active"):
        lines.append(
            f"- **Remote session**: ACTIVE"
            f" (since {state.get('rustdesk_session_start', '?')})"
        )

    pending_cmds = state.get("pending_commands", [])
    if pending_cmds:
        lines.append(
            f"- **Pending commands**: {', '.join(pending_cmds[:5])}"
        )
